### ISSUE TITLE
Missing bills in sitemaps

### ISSUE THREAD

**Issue by jonquandt** [usgpo/sitemap#2]
From https://github.com/usgpo/bulk-data/issues/21:

@edgarshvaykovsky said:
>Hello,
>
>We have found that there is no information about several bills in the sitemap of gpo.gov.
For example, BILLS-115s1445is.xml is introduced on https://www.gpo.gov/fdsys/bulkdata/BILLS/115/1/s
but there is no such item in sitemap >https://www.gpo.gov/smap/fdsys/sitemap_2017/2017_BILLS_sitemap.xml

Confirmed the issue and looking for additional examples.

**Comment by jonquandt** [comment]
@edgarshvaykovsky -- if you have additional examples, let me know. That will help us troubleshoot the problem.

**Comment by edgarshvaykovsky** [comment]
I have compared bills from two sources:
- https://www.gpo.gov/fdsys/bulkdata/BILLS/115/1
- https://www.gpo.gov/smap/fdsys/sitemap_2017/2017_BILLS_sitemap.xml

and discovered, that sitemap.xml (the second source) does not contain bills:

bills-115s1414is
bills-115s1431is
bills-115s1441is
bills-115s1410is
bills-115s1428is
bills-115s1446is
bills-115hr3162rh
bills-115s1417is
bills-115s1445is
bills-115s1448is
bills-115s1439is
bills-115s1416is
bills-115s1438is
bills-115s1447is
bills-115s1429is
bills-115s1418is
bills-115s1449is
bills-115s1443is
bills-115s1440is
bills-115s1420is
bills-115s1430is
bills-115hr3033ih
bills-115s1406is

**Comment by edgarshvaykovsky** [comment]
@jonquandt Any updates on this issue?

**Comment by jonquandt** [comment]
@edgarshvaykovsky - we've identified why some bills and other packages aren't showing up in the sitemap. We're looking into the best way to get them added into the sitemaps now.

**Comment by jonquandt** [comment]
Sitemaps have been updated and the bills have been added.
