### ISSUE TITLE
CREC sitemaps don't show all issues for multi-issue days

### ISSUE THREAD

**Issue by djrobinson** [usgpo/sitemap#9]
I'm having an issue with this sitemap today: https://www.govinfo.gov/sitemap/CREC_2022_sitemap.xml

The May 11th and May 19th Congressional Record included multiple issues of Senate proceedings:

**May 11**
- https://www.govinfo.gov/app/details/CREC-2022-05-11-i79
- https://www.govinfo.gov/app/details/CREC-2022-05-11-i80

**May 19**
- https://www.govinfo.gov/app/details/CREC-2022-05-19-i86 
- https://www.govinfo.gov/app/details/CREC-2022-05-19-i87

I believe when the second issue is posted for a given day it is overwriting the first. 

I crawled the site this morning and originally received this entry for 5/19/2022:
```
<url>
<loc>https://www.govinfo.gov/app/details/CREC-2022-05-19</loc>
<lastmod>2022-05-20T12:34:00.006Z</lastmod>
<changefreq>monthly</changefreq>
<priority>1.0</priority>
</url>
```

Later in the day, the entry above disappeared and this new one appeared:
```
<url>
<loc>https://www.govinfo.gov/app/details/CREC-2022-05-19-i87</loc>
<lastmod>2022-05-20T13:35:00.732Z</lastmod>
<changefreq>monthly</changefreq>
<priority>1.0</priority>
</url>
```
You can observe the same issue for 5/11.

The first issue of they day should be retained in the sitemap after the second issue is released.

**Comment by jonquandt** [comment]
@djrobinson thanks for pointing this out. We’ll see  how we can best address this.

you may also be interested in checking out the *collections* endpoint of the govinfo API:

https://api.govinfo.gov/collections/CREC/2022-05-11T00:00:00Z?offset=0&pageSize=100&api_key=DEMO_KEY

this will return any CREC packages that have been added or updated since 2022-05-11T00:00:00Z in JSON, and will provide links to content and metadata.

more info at https://api.govinfo.gov/docs

**Comment by djrobinson** [comment]
Oh awesome! The collections endpoint looks much better suited for my daily crawls so I'll start working with this. Thanks @jonquandt

**Comment by jonquandt** [comment]
Updating this card to note that the sitemaps are now reflecting multiple issues when they appear. For example:

https://www.govinfo.gov/sitemap/CREC_2024_sitemap.xml

has two packages associated with CREC-2024-01-03:
- CREC-2024-01-03-v169
- CREC-2024-01-03-v170.

It also has an instance of multiple issues on the same day with a different issue number, but same volume:
- CREC-2024-04-15-i64
- CREC-2024-04-15-i65
